### ISSUE TITLE
Add a system for instant runnof

### ISSUE THREAD

**Issue by jmrtns** [peer/mind#175]
For example if manager elections are to be done with this system and more than two people run instant runoff can be beneficial. Also, each manager getting their own page seems to take up a lot of space right now, not sure if there's a better way to do this.

**Comment by mitar** [comment]
No. Range voting we are using are superior. You pick the one with higher average.

http://rangevoting.org/rangeVirv.html
https://en.wikipedia.org/wiki/Range_voting#Example

**Comment by mitar** [comment]
> Also, each manager getting their own page seems to take up a lot of space right now, not sure if there's a better way to do this.

This should be addressed with #162.

**Comment by jmrtns** [comment]
Is it just me or do the manager election results look extremely polar thus far. Is that normal?

**Comment by mitar** [comment]
That is a good question. We do not have data from previous years (or do we, could we find it somewhere, @mkanwal?) to compare. But previous elections at the beginning of the semester with this software was similar. One reason might be that this is because the results are public from the beginning so the population goes with the perceived initial trend. But for other motions not related to elections there are examples where population went in a different way than the initial trend was. So personally I think this polarization is simply how it is and is not related to the use of this software. But it is definitely a great question.

**Comment by mkanwal** [comment]
It's quite possible that the polarity is due to results being continuously visible.  This is something we argued about initially.  Mitar said that having people see results may sway members towards a consensus where they will agree with the popular option rather.  This can be both good and bad: If a member was misinformed about a candidate, then they will self-correct potentially, but on the other hand, psychologically, people may want to feel like their candidate won, so they will compromise their original vote.
