### ISSUE TITLE
Dockerfile?

### ISSUE THREAD

**Issue by OliverEvans96** [peer/mind#214]
Is this really all you need? I feel like there should be more here

```
FROM tozd/meteor:ubuntu-xenial

ENV METEOR_STORAGE_CHOWN=

COPY ./docker/etc /etc
```

I'd like to contribute a kubernetes YAML when I get some time.

I hope everything is going well!
Oliver

**Comment by mitar** [comment]
Yea, because everything else is in upstream image: https://github.com/tozd/docker-meteor/blob/master/ubuntu-xenial.dockerfile

Many Meteor apps are similar. So I have a Docker image for all of them. There is a bit more in `docker-source.sh` file as well. It also runs during Docker build.

This Dockerfile is meant for production. So it does not have MongoDB. You will need it.

**Comment by mitar** [comment]
And yes, contributions welcome. :-)

**Comment by OliverEvans96** [comment]
Great, thanks! I'll have to learn a bit more about Meteor apps. I'll be in touch!

**Comment by mitar** [comment]
Are you back to Berkeley?

**Comment by mitar** [comment]
Yea. :-)
