### ISSUE TITLE
Better name

### ISSUE THREAD

**Issue by wrought** [peer/mind#35]
discuss!

ideas:

- groupthink
- granola
- decide-together
- work-together
- good-faith-collaboration
- decision procedure
- decision process
- decision-maker
- decision-hacker

**Comment by wrought** [comment]
- nutritional yeast

**Comment by mitar** [comment]
cc @wrought, @mkanwal, @subjective, @sunnysideofthescreen, @jmrtns

**Comment by mitar** [comment]
* comb (we comb through ideas to find good ones)
* feces (facilitator supreme, results of cloacas working together)

**Comment by mitar** [comment]
What about simply: "mot"?

**Comment by mitar** [comment]
More:
* motak
* tokam
* omot

**Comment by radiolarian** [comment]
clowncil

**Comment by wrought** [comment]
I still like "groupthink"...

**Comment by mitar** [comment]
I am probably going with "mot". Any objections?

**Comment by wrought** [comment]
I don't feel compelled toward mot, and it's your project, so if it's gotta be mot, I can't really stop you.

one last shot though:

"meetingrobot"

It's accurate to what it is, and unique enough for no good search results to show up.

**Comment by wrought** [comment]
"councilrobot" might be even better

**Comment by mitar** [comment]
"motbot"?

**Comment by mitar** [comment]
> I don't feel compelled toward mot, and it's your project, so if it's gotta be mot, I can't really stop you.

It is the best one from all I heard until now.

"groupthink" has a negative connotation. And also GitHub name is taken.

**Comment by subjective** [comment]
I like the word "assembly" because it refers to a political gathering but also alludes to computing/programming.

**Comment by mitar** [comment]
Hm, I think Googling "assembly" would not find this app for some time.

"coassembly"?

**Comment by sunnysideofthescreen** [comment]
objection to “mot” but i don’t have much of a replacement, it just sounds funny (not in the good way).

**Comment by mitar** [comment]
It means "word" in French.

**Comment by sunnysideofthescreen** [comment]
cloyne canvass ?

**Comment by mitar** [comment]
I think it should be something general, not necessary linked to Cloyne (other communities can use it as well).

**Comment by subjective** [comment]
So, for a collaborative editor with voting, I came up with the name "votepad" (vote + notepad). I have the .org domain.

That'd be a good name for the [Massive online collaborative decision-making system](http://mitar.tnode.com/post/73930434538/massive-online-collaborative-decision-making). But that's not the scope of this project, right? (It's been a while since I last ran it.)

**Comment by sunnysideofthescreen** [comment]
what if you called it just that: “assembly”?

**Comment by mitar** [comment]
> But that's not the scope of this project, right?

No, or at least not yet. Maybe in the future some feature can resemble that.

**Comment by sunnysideofthescreen** [comment]
@jakelerner votes "assemblance"

**Comment by mitar** [comment]
This sounds like "assemblage".

Tell him to try harder

**Comment by mitar** [comment]
"methink"?

**Comment by sunnysideofthescreen** [comment]
veto.
(you're not a 12th century knight-jake)

**Comment by sunnysideofthescreen** [comment]
assemblage:  "Assemblage theory asserts that, within a body, the relationships of component parts are not stable and fixed; rather, they can be displaced and replaced within and among other bodies, thus approaching systems through relations of exteriority" (wiki)

**Comment by subjective** [comment]
Deleuze and Guattari is a rich source of edgy software names. :-)

There is also "assembler", which makes sense and might be easier to find than both "assembly" and "assemblage". The only problem is that it already refers to a type of software.

**Comment by mitar** [comment]
So, the problem with those words written with double s and stuff like that they are not really global. People in non-English speaking countries will have issues knowing how to read them.

**Comment by mitar** [comment]
"peerthink"?

**Comment by mitar** [comment]
"lokom"

**Comment by mitar** [comment]
cc @jure

**Comment by sunnysideofthescreen** [comment]
peerthink is cool 👍

**Comment by mitar** [comment]
More ideas from Jake:
* commonsense
* thinkabout

**Comment by mitar** [comment]
cc @CdavM

**Comment by mitar** [comment]
Ha ha, the list of episodes really align with this app: https://en.wikipedia.org/wiki/Thinkabout_%28U.S._TV_series%29

**Comment by camillevilla** [comment]
...how about...
Sheaf? Like when you harvest a bunch of wheat and tie it together.

**Comment by subjective** [comment]
"Sheaf" is elegant. It also refers to a concept in algebraic geometry:

http://mathworld.wolfram.com/Sheaf.html

**Comment by subjective** [comment]
"Sheaf" can also be a playful variation of "chief", since the app is a facilitator but not a boss.

**Comment by mitar** [comment]
* okio
* raeo
* ateo

**Comment by subjective** [comment]
okio is a project with 2k stars: https://github.com/square/okio

ateo means atheist in Spanish and Italian. :-)

**Comment by mitar** [comment]
How do you say "spark" in some other language?

**Comment by subjective** [comment]
* faísca (Portuguese)
* chispa (Spanish, Portuguese)

My favorite is:
* ignis (Latin)

**Comment by jure** [comment]
What we really need to settle this is a kind of online voting system, something that would modernize this archaic decision making process.

But to continue in the way of the old masters, I really liked the "commonsense" thread, but perhaps to offer some kind of analogy to the internet introduced "crowdsource" or "crowdfunding": **Crowdsense** would be a good option.

I dislike the foreign language options since they're not easy to remember, mostly, unless you know the language they're from, which is a bit exclusive :)

Also, stumbled across a relevant illustration that I really liked:
![image](https://cloud.githubusercontent.com/assets/238667/14639737/72f83e52-063e-11e6-8287-e4e8ca21bd00.png)

**Comment by ninabreznik** [comment]
I like names that kind of describe or at least offer the association with what the project is about (a metaphor) so I can store it in my brain more easily :)

So the words describing the project are:
groupthink, decide-together, work-together, good-faith-collaboration, decision procedure, decision process, decision-maker, decision-hacker 

So let's see some more ideas/combinations/metaphors:
- groupthink  (saw it above, 2 syllables, memorable...) 👍 
- peerThink (saw it above, 2 syllables, memorable...) 👍 
- peerAction? (similar, but more about the benefits of working together)
- teamVote?
- voteBoost?

Some quick ideas... Otherwise, when I do brainstorming about names, my biggest friends are Google images search and good old Synonyms search http://www.thesaurus.com/browse/collaboration?s=t

Good luck with the project, we were also brainstorming a lot about similar thing, but more in the sense of co-owning and then co-deciding for sharing income, tasks, strategy etc.

**Comment by mkanwal** [comment]
+1 "sheaf"

**Comment by mitar** [comment]
> What we really need to settle this is a kind of online voting system, something that would modernize this archaic decision making process.

You are right, we could put it through a vote through the system itself. ;-)

But I think we can also manage through GitHub, comments and also upvoting it supports now.

I like the "Crowdsense" idea, but "crowd" has negative connotation. Also, Wikipedia is not really "crowdsourcing", because that is more like "outsourcing". So in fact "crowd" is often opposite to community. In "crowd" you do work for somebody else. In community you do it for yourself.

"commonsense" I like because you can play with words and get "commons essence". :-)

**Comment by mitar** [comment]
Some more names proposed from the Cloyne community:
* #cloynecouncil
* clomittee
* execloyne
* clonference
* cloncave
* online clonecil
* Quorum Corrall
* The Coup
* clouncil
* The Count of Monte Council
* Stewart
* Elizabeth

**Comment by mitar** [comment]
* commondecide
* DecideTogether
* WeDecide
* ReachDecision
* ReachD
* GraspD
* decsense
* sense decision
* sensed
* desense

**Comment by mitar** [comment]
* sense bubble
* bubble sense
* essencesense
* crowdessence
* populus
* populus sense
* popul

**Comment by mitar** [comment]
* pleo
* plenus
* [manipulus](https://en.wiktionary.org/wiki/manipulus)
* [manus](https://en.wiktionary.org/wiki/manus) – means "hand", I really like it

**Comment by mitar** [comment]
Even better two:
* popular (by, of or for the people)
* popularis

**Comment by mitar** [comment]
I got another suggestion:
* d-voice (Democracy voice / the voice)

**Comment by wrought** [comment]
I really like:

- werthink
- votepad
- ethervote!!!!

**Comment by wrought** [comment]
- peerdo

**Comment by ecawthon** [comment]
@subjective 
> Deleuze and Guattari is a rich source of edgy software names. :-)

Seconded. I nominate "Rhiz-o-matic"

**Comment by ecawthon** [comment]
We could incorporate "Moo-" as a hat tip to Cloyne's practice of using "moo" for abstentions, as well as a reference to "massive online open - "

**Comment by mitar** [comment]
moovote?

**Comment by ecawthon** [comment]
Mootion?
Moovement?
GroupMoo?
PeerMoo?
QuoruMoo?

**Comment by ecawthon** [comment]
Really I like some of the names above better. There are plenty of other places "moo" could be incorporated. I think [Group-|Peer-][Think|Vote] are my favorites. And Rhiz-o-Matic. Other stems to play with might be libre/open (descriptive), or consensus (con-sense-us? CanSenseUs?)

**Comment by subjective** [comment]
I like the "moo" reference to Cloyne abstentions! :-)

What about "peervote"? Simple, easy, descriptive, two syllables, no competition for namespace.

**Comment by wrought** [comment]
I like moo a lot too!

- yeamoo
- naymoo
- yeanaymoo
- nayeamoo
- yaymoo!!!!

**Comment by mitar** [comment]
Nobody likes 'popularis"? :-(

**Comment by wrought** [comment]
moopop?

**Comment by samod** [comment]
deliberapp - an app for deliberation.

**Comment by mitar** [comment]
Some more ideas:
* dide (shorter for decide)
* converge
* molop
* interverge
* propose

**Comment by mitar** [comment]
OK, I went over the list of all ideas and made a shortlist. Let's converge. Which one do you like:
* votepad
* peerthink
* sheaf
* popularis
* d-voice
* wethink
* ethervote
* mootion

**Comment by mitar** [comment]
I am not sure about using vote in the name, because we might not necessary always use voting for making decisions.

**Comment by jure** [comment]
PeerThink

**Comment by mitar** [comment]
One more project starting with "peer"?

**Comment by mitar** [comment]
More ideas:
* Apò mēkhanês theós
* ODP- Ol' Dirty Polis
* Omnipol

**Comment by mitar** [comment]
One more idea:
* mood (moo + decisions)

There are my current thoughts:
* I would not like to start it with peer, because I have too many projects starting with peer already. :-)
* I am also thinking, that it should be a name a government official would be OK using, because eventually we would want this tool to be used also inside formal settings. In that context, what I am thinking, is that the easiest approach to "sell" the app is an app for polling what constituency thinks/opinions, or to include them more in decision making. So something like https://petitions.whitehouse.gov/.

**Comment by mitar** [comment]
On the other note, I managed to get the https://github.com/peer organization. :-)

**Comment by mitar** [comment]
* PeerBuilder
* PeerDecide
* PeerGroup
* PeerMe
* PeerUs

**Comment by mitar** [comment]
What about codecide?

PeerAssembly?

**Comment by mitar** [comment]
I moved it to: https://github.com/peer/decide

Not sure if name should be "PeerDecide" or just "Decide".

"PeerDecide" counds too much like herbicide or genocide or homicide. :-)

**Comment by mitar** [comment]
Maybe names should be spaces where you do something. Like "peer library" - you read with peers. So what are spaces where you make decisions together?

**Comment by mitar** [comment]
Decided on PeerMind.

**Comment by mitar** [comment]
(Discussion and feedback still open.)
