### ISSUE TITLE
add "reopen motion" button

### ISSUE THREAD

**Issue by wrought** [peer/mind#40]
makes the process for a motion a bit more like a loop, and allows for correcting mistakes that might have been made. otherwise, the user has to make a new motion.

**Comment by mitar** [comment]
What mistakes? If they by accident closed closed the motion?

**Comment by wrought** [comment]
Yes, like if you closed too early, or a clarification came up out-of-band
and it needed to be re-settled for the record and posterity (admin feature)

**Comment by mitar** [comment]
After more thought I think we should instead allow simple copying of an existing motion. This addresses other features (like somebody wanting to propose a slightly different version of a motion), but also simulates reopening.

See #144.

**Comment by mitar** [comment]
Otherwise it is unclear what to do with votes which were before closing of a motion. So you have motion, it is opened, people vote, you close it, and you reopen it, is voting restarted? If we leave previous votes active, how long has been motion open? From before, and then a pause, then again? So simply start-end is not enough, you have breaks in between. This feels like it can introduce misuse because some motion might look like it was opened a long time, but in fact it was not because part of the time was closed.
